<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.github.jjb-coding</groupId>
        <artifactId>trellis-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>trellis-example</artifactId>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>
                                java
                            </goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>com.github.jjbcoding.trellis.example.app.Main</mainClass>
                </configuration>

            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.github.jjbcoding.trellis.example.app.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <properties>
        <maven.compiler.release>16</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.jjb-coding</groupId>
            <artifactId>trellis</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.jjb-coding</groupId>
            <artifactId>trellis-swing</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>